owater/landdingpage/urls.py
from django.urls import path

from .utilities import orderProducts
from . import views
from .views import about, contact, deliveryPolicy, detail, detailOrder, home, listOrder, order, orderInfo, orderSuccess, products, returnPolicy
from django.views.generic import TemplateView

urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('products', products, name='products'),
    path('detail/<str:type>', detail, name='detail'),
    path('order', order, name='order'),
    path('order-information', orderInfo, name='orderInfo'),
    path('order-success/<str:idorder>', orderSuccess, name='orderSuccess'),
    path('delivery-policy', deliveryPolicy, name='deliveryPolicy'),
    path('return-policy', returnPolicy, name='returnPolicy'),
    path('detail-order/<str:idorder>', detailOrder, name='detailOrder'),

    path('listOrder', listOrder, name='listOrder'),
    # funtion
    path('order-products', orderProducts, name='orderProducts'),

    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type="application/xml")),
]

owater/owater/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landdingpage.urls')), 
]

owater/landdingpage/models.py
from django.db import models

# Create your models here.

owater/landdingpage/forms.py
from django import forms

class formInfo(forms.Form):
    username  = forms.CharField()
    phone = forms.CharField()
    address = forms.CharField()
    province = forms.CharField()
    email = forms.CharField()
    note = forms.CharField()
    dataOder = forms.CharField()
    total = forms.CharField()

owater/landdingpage/views.py
from django.shortcuts import render

from .forms import formInfo
from firebase_admin import firestore
db = firestore.client()
import json

# Create your views here.
def home(request):
    metaData = {
        "page_description" : "Nước uống Kangen được tạo ra qua quá trình điện giải do người Nhật sáng tạo ra, ngày càng được nhiều người ưa chuộng nhờ vào những lợi ích sức khỏe tuyệt vời mà nó mang lại. Với công nghệ tiên tiến được nhập khẩu từ Nhật Bản, nước uống Kangen OWA có nồng độ ion hydroxide cao, hỗ trợ sức khỏe tổng quát bằng cách giúp cơ thể loại bỏ các gốc tự do có hại. Điều này giúp ngăn ngừa quá trình lão hóa, tăng cường hệ miễn dịch và giảm nguy cơ mắc các bệnh mãn tính như tiểu đường và bệnh tim mạch.",
        "page_og_url" : "https://www.owa.vn/",
        "page_keywords" : 'nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe ',
        "page_title" : "OWA Vietnam",
        "page_image" : "https://www.owa.vn/static/assets/imgs/banners/Banner_Social.webp",
    }
    return render(request, 'home.html',{
        "metaData" : metaData
    })
def about(request):
    metaData = {
        "page_description" : "Công ty TNHH OWA Việt Nam là doanh nghiệp tiên phong trong lĩnh vực nước uống Kangen tại thị trường Việt Nam. Vời chất lượng nước ion kiềm số 1 thị trường Việt Nam, chúng tôi cam kết mang tới sản phẩm nước ion kiềm chất lượng cao, được sản xuất theo tiêu chuẩn quốc tế, với độ pH lên tới 9,5 và nồng độ ion hydroxide cao, giúp cân bằng độ pH trong cơ thể. Theo nghiên cứu của học viện Y khoa Hoa Kỳ, nước ion kiềm cùng với các nguyên tố vi lượng kết hợp có tác dụng tích cực cho sức khỏe.",
        "page_og_url" : "https://www.owa.vn/about",
        "page_keywords" : 'nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe ',
        "page_title" : "Về OWA",
        "page_image" : "https://www.owa.vn/static/assets/imgs/banners/Banner_Social.webp",
    }
    return render(request, 'about.html',{
        "metaData" : metaData
    })
def products(request):
    metaData = {
        "page_description" : "Nước uống Kangen được tạo ra qua quá trình điện giải do người Nhật sáng tạo ra, ngày càng được nhiều người ưa chuộng nhờ vào những lợi ích sức khỏe tuyệt vời mà nó mang lại. Với công nghệ tiên tiến được nhập khẩu từ Nhật Bản, chúng tôi xin giới thiệu đến bạn các sản phẩm nước uống ion kiềm chất lượng cao của mình.",
        "page_og_url" : "https://www.owa.vn/products",
        "page_keywords" : 'nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe ',
        "page_title" : "Sản Phẩm",
        "page_image" : "https://www.owa.vn/static/assets/imgs/Slide_4_fulltext.webp",
    }
    return render(request, 'products.html',{
        "metaData" : metaData
    })

def deliveryPolicy(request):
    metaData = {
        "page_description" : "Chính sách giao hàng",
        "page_og_url" : "https://www.owa.vn/",
        "page_keywords" : 'nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe ',
        "page_title" : "Chính sách giao hàng",
        "page_image" : "https://www.owa.vn/static/assets/imgs/banners/Untitled-2.webp",
    }
    return render(request, 'seemore/delivery_policy.html',{
        "metaData" : metaData
    })
def returnPolicy(request):
    metaData = {
        "page_description" : "Chính sách đổi trả hàng.",
        "page_og_url" : "https://www.owa.vn/return-policy",
        "page_keywords" : 'nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe ',
        "page_title" : "Chính sách đổi trả hàng",
        "page_image" : "https://www.owa.vn/static/assets/imgs/banners/Untitled-2.webp",
    }
    return render(request, 'seemore/return_policy.html',{
        "metaData" : metaData
    })
def detail(request,type):
    if type == "A3" :
        metaData = {
            "page_description" : "NƯỚC UỐNG KANGEN OWA TYPE A3 - PH 8.0-8.5. Giá bán: 45.000đ. Owarter bình 20L là loại nước cao cấp, khoáng chất hoàn toàn tự nhiên. Có nồng độ pH nhẹ, vị ngọt thanh mát, phù hợp cho người mới bắt đầu sử dụng nước ion kiềm.",
            "page_og_url" : "https://www.owa.vn/detail/A3",
            "page_keywords" :"nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe, Calcium: 80, Magnesium: 40, Potassium: 2, Sodium: 6.5, Nitrates: 3.8, Bicarbonates: 360, Sulfates: 3, Silica: 10, Chloride:s 0.7, PH: 8.0-8.5 ",
            "page_title" : "NƯỚC UỐNG KANGEN OWA TYPE A3",
            "page_image" : "https://www.owa.vn/static/assets/imgs/products/Binh%20nuoc%20A3.webp",
        }
        return render(request, 'details/detail_A3.html',{
        "metaData" : metaData
    })
    if type == "A2" :
        metaData = {
             "page_description" : "NƯỚC UỐNG KANGEN OWA TYPE A2 - PH 8.5-8.9. Giá bán: 65.000đ. Owarter bình 20L là loại nước cao cấp, khoáng chất hoàn toàn tự nhiên. Có độ pH vừa, vị ngọt thanh mát, giúp trung hòa các gốc axit trong cơ thể, cân bằng pH.",
            "page_og_url" : "https://www.owa.vn/detail/A2",
            "page_keywords" :"nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe,Calcium: 80, Magnesium: 40, Potassium: 2, Sodium: 6.5, Nitrates: 3.8, Bicarbonates: 360, Sulfates: 3, Silica: 10, Chloride:s 0.7, PH: 8.5-8.9.",
            "page_title" : "NƯỚC UỐNG KANGEN OWA TYPE A2",
            "page_image" : "https://www.owa.vn/static/assets/imgs/products/Binh%20nuoc%20A2.webp",
        }
        return render(request, 'details/detail_A2.html',{
        "metaData" : metaData
    })
    if type == "A1" :
        metaData = {
           "page_description" : "NƯỚC UỐNG KANGEN OWA TYPE A1 - PH 9.0-9.5. Giá bán: 100.000đ. Owarter bình 20L là loại nước cao cấp, khoáng chất hoàn toàn tự nhiên. Đặc biệt tốt cho cơ thể với độ pH cao, nồng độ ion hydroxide cao, vị ngọt thanh mát, trung hòa các gốc axit có hại, tốt cho người bị axit dạ dày, gout, và các bệnh liên quan đến axit dư thừa.",
            "page_og_url" : "https://www.owa.vn/detail/A1",
            "page_keywords" : "nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe,Calcium: 80, Magnesium: 40, Potassium: 2, Sodium: 6.5, Nitrates: 3.8, Bicarbonates: 360, Sulfates: 3, Silica: 10, Chloride:s 0.7, PH:  9.0-9.5",
            "page_title" : "NƯỚC UỐNG KANGEN OWA TYPE A1",
            "page_image" : "https://www.owa.vn/static/assets/imgs/products/Binh%20nuoc.webp",
        }
        return render(request, 'details/detail_A1.html',{
        "metaData" : metaData
    })
def order(request):
    metaData = {
        "page_description" : "OWA Vietnam Co., Ltd - Chuyên cung cấp nước uống tinh khiết, đảm bảo chất lượng và an toàn cho sức khỏe. Sự lựa chọn hàng đầu cho gia đình và doanh nghiệp.",
        "page_og_url" : "https://www.owa.vn/",
        "page_keywords" : "nước kangen, nước owa, nước tốt cho sức khỏe,kangen, owa, owarte , i-on kiềm ,  OWA HIGH OXYGEN, Độ pH cao lên đến 9.5, Nồng độ i-on Hydroxide cao, Nguồn gốc tự nhiên, Độ tinh khiết cao,pH ổn định, Không xử lý hóa học, Hỗ trợ sức khỏe,",
        "page_title" : "OWA Vietnam",
        "page_image" : "https://www.owa.vn/static/assets/imgs/banners/Banner_Social.webp",
    }
    return render(request, 'order.html',{
        "metaData" : metaData
    })
def listOrder(request):
    listOrder = []
    order_ref = db.collection('orders').stream()
    for item in order_ref :
        data = item.to_dict()
        id = data['id']
        dataOder =[]
        product_ref = db.collection("orders").document(id).collection("products").stream()
        for itemproduct in product_ref :
            dataOder.append(itemproduct.to_dict())
        data.update({
            "dataOder" : dataOder ,
            })
        print (data)
        listOrder.append(data)
    return render(request, 'listOrder.html',{
        "listOrder" : listOrder,
    })

def orderSuccess(request ,idorder):
    print("idorder", idorder)
    if not idorder : 
        return 
    requestData = db.collection('orders').document(idorder).get().to_dict()
    product_ref = db.collection("orders").document(idorder).collection("products").stream()
    dataOder = []
    for itemproduct in product_ref :
        dataOder.append(itemproduct.to_dict())
    requestData.update({
        "dataOder" : dataOder ,
        })
    print("requestData",requestData)
    metaData = {
        "page_description" : "OWA Vietnam Co., Ltd - Chuyên cung cấp nước uống tinh khiết, đảm bảo chất lượng và an toàn cho sức khỏe. Sự lựa chọn hàng đầu cho gia đình và doanh nghiệp.",
        "page_og_url" : "https://www.owa.vn/",

owater/landdingpage/templates/about.html
{% extends "index.html" %}
{% load static %}
{% block main-content %}
<main>
    <div class="nxPaddingPage">
        <div class="container text-center">
            <div class="mt-5">
                <h1 class="">Về OWA</h1>
                <p>
                    Công ty TNHH OWA Việt Nam là doanh nghiệp tiên phong trong lĩnh vực nước uống Kangen tại thị trường Việt Nam. Vời
                    chất lượng nước ion kiềm số 1 thị trường Việt Nam, chúng tôi cam kết mang tới sản phẩm nước ion kiềm chất lượng cao, 
                    được sản xuất theo tiêu chuẩn quốc tế, với độ pH lên tới 9,5 và nồng độ ion hydroxide cao, 
                    giúp cân bằng độ pH trong cơ thể. Theo nghiên cứu của học viện Y khoa Hoa Kỳ, 
                    nước ion kiềm cùng với các nguyên tố vi lượng kết hợp có tác dụng tích cực cho sức khỏe. 
                </p>
                <img  loading="lazy"  src="{% static '/assets/imgs/baovenguonnuoc.webp' %}" alt="owa" srcset="">
            </div>
            <div class="mt-5">
                <h2>Nước uống Kangen</h2>
                <p>
                    Nước uống Kangen OWA High Oxygen được nghiên cứu và phát triển bởi công ty TNHH OWA Việt Nam, 
                    từ nguồn nước tự nhiên tươi mát kết hợp với công nghệ nâng cao Oxy trong nước.
                </p>
                <img  loading="lazy"  src="{% static '/assets/imgs/image_2.webp' %}" alt="owa" srcset="">
            </div>
            <div class="mt-5">
                <h2>Cam Kết Chất Lượng</h2>
                <p>
                    OWA cam kết đem đến cho khách hàng sản phẩm chất lượng, an toàn và hiệu quả. Chúng tôi sử dụng công nghệ tiên tiến và quy trình sản xuất khép kín để đảm bảo chất lượng nước ion kiềm tốt nhất. Ngoài ra, OWA còn đáp ứng nhu cầu của khách hàng với nhiều dòng sản phẩm đa dạng và tiện lợi như nước uống, nước tinh khiết, nước ion kiềm, nước nóng lạnh và máy lọc nước. Chúng tôi cam kết mang đến cho khách hàng dịch vụ tốt nhất và giá cả hợp lý.
                </p>
                <img  loading="lazy"  src="{% static '/assets/imgs/image_1.webp' %}" alt="owa" srcset="">
            </div>
           
        </div>
    </div>
</main>
{% endblock main-content %}

owater/landdingpage/templates/contact.html
{% extends "index.html" %}
{% load static %}
{% block main-content %}
<main>
    <div class="nxPaddingPage">
        <div class="container">
            <h1 class="text-center page-title">Thông tin liên hệ</h1>
            <div class="row row-contact">
                <div class="col-6 col-contact center-flex  ">
                    <img  loading="lazy"  src="{% static '/assets/imgs/image_contact.webp' %}" alt="Owater bình 20L">
                </div>
                <div class="col-6 col-contact mb-5" >  
                    <div class=" w-full" >
                        <div class="py-2">
                            <h4>Địa chỉ mua hàng</h4>
                            <p><i class="fa-solid fa-location-dot"></i> Tầng 1 Tòa nhà i9 Khuất Duy Tiến, Phường Thanh Xuân Bắc, Quận Thanh Xuân, Hà Nội, Vietnam</p>
                        </div>
                        <div class="py-2">
                            <h4>Facebook</h4>
                            <a href="https://www.facebook.com/OWAHighOxygen" target="_blank" title="cOWAHighOxygen" rel="nofollow">
                                <i class="fa-brands fa-facebook"></i>
                                <span>https://www.facebook.com/OWAHighOxygen</span>
                            </a>
                        </div>
                        <div class="py-2">
                            <h4>Gmail</h4>
                            <a href="#"> ✉ owavietnam@gmail.com</a>
                        </div>
                        <div class="py-2">
                            <h4>Số điện thoại</h4>
                            <a href="tel:19008942"> ☎ 1900 8942</a>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock main-content %}

owater/landdingpage/templates/google709fd28d435b0072.html
google-site-verification: google709fd28d435b0072.html

owater/landdingpage/templates/orderInfo.html
{% extends "index.html" %}
{% load static %}
{% block main-content %}
<main>    
    <div class="nxPaddingPage">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-8">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="title">Thông tin đặt hàng</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label for="">Họ và tên <span style="color: red;" title="Bắt buộc">*</span> </label>
                                <input id="username" type="text" class="form-control" required="required" name="txtName" minlength="3" maxlength="40" value="" placeholder="Họ và tên">
                                <p class="text-red d-none" id="error_username"></p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label for="">Số điện thoại <span style="color: red;" title="Bắt buộc">*</span> </label>
                                <input  id="phone" type="tel" name="txtPhone" required="required" value="" minlength="5" maxlength="15" class="form-control" placeholder="Số điện thoại">
                                <p class="text-red d-none" id="error_phone"></p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group ">
                                <label  for="">Địa chỉ <span style="color: red;" title="Bắt buộc">*</span> </label>
                                <input  id="address" type="text" class="form-control" required="required" name="txtAddress" minlength="3" maxlength="200" value="" placeholder="Địa chỉ">
                                <p class="text-red d-none" id="error_address"></p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group ">
                                <label for="">Tỉnh / Thành phố <span style="color: red;" title="Bắt buộc">*</span> </label>
                                <input  id="province" type="text" class="form-control" name="txtCity" value="" minlength="3" maxlength="30" required="required" placeholder="Tỉnh / Thành phố ">
                                <small >(Hiện chỉ giao ở các tỉnh Hà Nội Và thành phố Hồ Chí Minh)</small>
                                <p class="text-red d-none" id="error_province"></p>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="">Email <em>(Không bắt buộc)</em>
                                </label>
                                <input id="email" type="email" name="txtEmail" value="" maxlength="80" class="form-control" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="">Ghi chú đơn hàng <em>(Không bắt buộc)</em>
                                </label>
                                <textarea id="note" class="form-control" name="note" rows="3" maxlength="500"  placeholder="Ghi chú đơn hàng "></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-4 border border-2 p-4">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2 class="text-center">Thông tin đơn hàng</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table gio-hang-table">
                                <thead>
                                    <tr>
                                        <th colspan="2">Sản phẩm</th>
                                        <th class="w-totalamount">Tổng tiền</th>
                                    </tr>
                                </thead>
                                <tbody id="list-product">
                                    <tr>
                                        <td>
                                            <img  loading="lazy"  src="{% static '/assets/imgs/products/Binh nuoc A3.webp' %}" width="50" alt="Evian chai nhựa 330ml (Thùng / 24 Chai)">
                                        </td>
                                        <td>OWA HIGH OXYGEN TYPE A1 × 1</td>
                                        <td class="link-red text-right">
                                            <strong>45.000đ</strong>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <strong>Tổng tiền</strong>
                                        </td>
                                        <td class="link-red text-right">
                                            <strong>45.000 đ</strong>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <ul style="list-style: none; padding: 0px; margin: 0px;">
                                <li>
                                    <h4>Thanh toán khi nhận hàng</h4>
                                    <div class="box">
                                        <p>
                                            <span style="text-align: center;">Đơn hàng đã được ghi nhận, chúng tôi sẽ liên hệ để xác nhận đơn hàng trong vòng 12 giờ (trong thời gian làm việc chúng tôi 8h00- 17h30 mỗi ngày). Đơn hàng không được chúng tôi gọi lại để xác nhận, đồng nghĩa đơn hàng này tự động huỷ vì không đủ điều kiện giao hàng!</span>
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-12 text-center">
                            <button id="btn-submit" class="btn-blue">
                                Đặt hàng
                            </button>
                            <p class="text-red d-none" id="error_dataOrder"></p>
                        </div>
                        <div class="col-sm-12">
                            <p style="padding-top: 15px;">Thông tin cá nhân của bạn sẽ được sử dụng để xử lý đơn đặt hàng của bạn. Chúng tôi không sử dụng thông tin này cho các bên thứ ba chính sách riêng tư.</p>
                        </div>
                        <div class="col-sm-12 text-center">
                            <a href="/order" title="Trở về giỏ hàng" class="btn-back">Trở về giỏ hàng</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</main>
<form class="hidden" id="formInfo">
    {% csrf_token %}
    {% for field in formInfoData %} 
        {{ field.label }} 
        {{ field }} 
    {% endfor %}

</form>
<script>
document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
            renderListProduct(cart)
    }, 100);
    function renderListProduct(cart) {
        const container = document.getElementById('list-product');
        if(!container){
            return
        }  
        let total = 0
        container.innerHTML = cart.map((item, index) =>{
            if(item.quantity > 0){
                total += item.price * item.quantity
                let row = `
                    <tr style="background-color:rgba(0,0,0,0.05); ">
                        <td>
                            <img  loading="lazy"  src="${item.imgSrc}" style="width:50px" alt="ơwater">
                        </td>
                        <td>${item.name} × ${item.quantity}</td>
                        <td class="link-red text-right">
                            <strong>${(item.price * item.quantity).toLocaleString('vi-VN')}đ</strong>
                        </td>
                    </tr>
                `
                return row
            }
        }).join('') + `
            <tr>
                <td colspan="2">
                    <strong>Tổng tiền</strong>
                </td>
                <td class="link-red text-right">
                    <strong>${total.toLocaleString('vi-VN')}đ</strong>
                </td>
            </tr>
        `;
    $("#id_total").val(total)
    }

    $("#username").on("change input",(e)=>{
        let value = e.target.value
        $("#id_username").val(value)
        $("#error_username").addClass("d-none")
    })
    $("#phone").on("change input",(e)=>{
        let value = e.target.value
        $("#id_phone").val(value)
        $("#error_phone").addClass("d-none")

    })
    $("#address").on("change input",(e)=>{
        let value = e.target.value
        $("#id_address").val(value)
        $("#error_address").addClass("d-none")

    })
    $("#province").on("change input",(e)=>{
        let value = e.target.value
        $("#id_province").val(value)
        $("#error_province").addClass("d-none")

    })
    $("#email").on("change",(e)=>{
        let value = e.target.value
        $("#id_email").val(value)

    })
    $("#note").on("change",(e)=>{
        let value = e.target.value
        $("#id_note").val(value)

    })
    getData()
    function getData(){
        let data = cart.filter((item, index) =>{
            if(item.quantity > 0){
                return {
                    id: item.id,
                    quantity: item.quantity,
                    type : item.type,
                    name: item.name,
                    price: 100000,
                    imgSrc: item.imgSrc
                }
            }
        })
        $("#id_dataOder").val(JSON.stringify(data))
    }
   
    $("#btn-submit").on("click",async ()=>{
        let check = checkValidate()
        if(check){
            try {
                const response = await $.ajax({
                    type: "POST",
                    url: "/order-products",
                    data: $("#formInfo").serialize(),
                });     
                console.log(response)
                if (response  && response.statusreturn === 'true') {
                    let idDocument = response.id;
                    resetCart()
                    alert('Đã đặt hàng thành công!');
                    window.location.href = '/order-success/' + response.id;
                }else{
    
                }
            } catch (error) {
                console.error(error);
            }
        }
    })
    function checkValidate(){
        let check = true
        if($("#id_username").val() === ""){
            check = false
            $("#error_username").removeClass("d-none").text("Vui lòng điền họ và tên!")
        }
        if($("#id_phone").val() === ""){
            check = false
            $("#error_phone").removeClass("d-none").text("Vui lòng điền số điện thoại!")
        }
        if($("#id_address").val() === ""){
            check = false
            $("#error_address").removeClass("d-none").text("Vui lòng điền địa chỉ!")
        }
        if($("#id_province").val() === ""){
            check = false
            $("#error_province").removeClass("d-none").text("Vui lòng điền Tỉnh, Thành phố!")
        }
        if($("#id_dataOder").val() === "[]"){
            check = false
            $("#error_dataOrder").removeClass("d-none").text("Bạn chưa chọn sản phẩm nào!")
        }
        return check 
    }
});


</script>
{% endblock main-content %}